export const BASE_URL = 'http://localhost:8080/#'
export const SERVER_URL = 'http://localhost:5000/'
export const ADMIN_ROUTE = '/admin';
export const LOGIN_ROUTE = '/login';
export const REGISTRATION_ROUTE = '/registration';
export const SHOP_ROUTE = '/';
export const BASKET_ROUTE = '/basket';
export const DEVICE_ROUTE = '/device';
export const ORDERING_ROUTE = '/ordering'
// export const devicesImgDirName = 'device/'
export const defaultDeviceImg = 'https://primevue.org/images/galleria/galleria15.jpg'
